language: python
before_install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install antlr4
install:
  - pip3 install -r requirements.txt
script:
  - antlr4 -Dlanguage=Python3 ./antlr/Grammar.g4
  - python3 -m pytest
